name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install backend dependencies
        run: npm install

      - name: Start backend
        run: npm start &

      - name: Wait for backend to be ready
        run: sleep 10

      - name: Test backend
        run: npm test

      - name: Install frontend dependencies
        working-directory: ./bloglist-frontend
        run: npm install

      - name: Check frontend style
        working-directory: ./bloglist-frontend
        run: npm run lint

      - name: Build frontend
        working-directory: ./bloglist-frontend
        run: npm run build

      - name: Start frontend
        working-directory: ./bloglist-frontend
        run: npm start &

      - name: Wait for frontend to be ready
        run: sleep 10

      - name: Check frontend tests
        working-directory: ./bloglist-frontend
        run: npm test

      - name: Run Playwright tests
        working-directory: ./bloglist-frontend
        run: npx playwright test

      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

      - name: Notify Discord of deployment success
        if: ${{ success() }}
        uses: sarisia/actions-status-discord@v1.15.0
        with:
          title: A new version of your app deployed
          status: Success
          color: 0x00ff00
          description: "Deployed by ${{ github.actor }}"
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: Github Actions

      - name: Notify Discord of build failure
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@v1.15.0
        with:
          title: Build failed
          status: Failure
          color: 0xff0000
          description: "Commit [${{ github.sha }}] broke the build"
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: Github Actions

  tag_release:
    needs: [deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
